Module 3 - MVC/Agenda/diary/diary/Models/broker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public broker()
        {
            this.appointments = new HashSet<appointment>();
        }
    
        public int idBroker { get; set; }

        [Required(ErrorMessage = "Champ requis")] //champ requis
        [StringLength(50)] // 50 caracs. max
        [DisplayName("Nom de famille")]
        public string lastName { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [StringLength(50)]
        [DisplayName("Prénom")]
        public string firstName { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [StringLength(100)]
        [RegularExpression(@"^[\w\.=-]+@[\w\.-]+\.[\w]{2,3}$", ErrorMessage = "Adresse mail non valide")] //regex mail
        [DisplayName("Adresse Mail")]
        public string mail { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [StringLength(10)]
        [RegularExpression(@"^0[0-9]{9}$", ErrorMessage = "Numéro de télephone non valide.")] //regex tél.
        [DisplayName("Numéro de télephone")]
        public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
    }
}

Module 3 - MVC/Agenda/diary/diary/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using diary.Models; // ajout du modèle

namespace diary.Controllers
{
    public class AppointmentController : Controller
    {
        private agendaEntities1 db = new agendaEntities1(); // nouvelle instance du model de la bdd
        // GET: AddAppointment | Affiche la page d'ajout d'un rendez-vous
        [HttpGet]
        public ActionResult AddAppointment(int? id)
        {
            if (id != null)
            {
                ViewBag.SelectedBroker = id;
            }
            // select query
            var selectBrokerQuery = from m in db.brokers
                                    select m;
            // passage de résultat sous forme de liste dans le viewbag
            ViewBag.ListBrokers = new SelectList(selectBrokerQuery, "idBroker", "lastName", ViewBag.SelectedBroker);
            // select query
            var selectCustomerQuery = from m in db.customers
                                      select m;
            // passage de résultat sous forme de liste dans le viewbag
            ViewBag.ListCustomers = new SelectList(selectCustomerQuery, "idCustomer", "lastName");
            return View("AddAppointment");
        }
        // POST: AddAppointment | ajoute un rendez-vous dans la bdd
        [HttpPost]
        public ActionResult AddAppointment(int? id, appointment newAppointment)
        {
            // si le rdv est fixé à une datetime supérieure à celle d'ajourd'hui, permettre l'insertion
            if (newAppointment.datHour > DateTime.Now)
            {
                // si l'heure choisie est inférieure à 8 heures, message d'erreur
                if (newAppointment.datHour.Hour < 8)
                {
                    // message d'erreur dans une alert js et retour à la dernière page
                    return Content("<script type='text/javascript'>alert('Les rendez-vous commencent à 8 heures.'); history.back();</script>");
                }
                // si l'heure choisie est supérieure à 18 heures, message d'erreur
                if (newAppointment.datHour.Hour > 18)
                {
                    // message d'erreur dans une alert js et retour à la dernière page
                    return Content("<script type='text/javascript'>alert('Les rendez-vous finissent à 18 heures.'); history.back();</script>");
                }
                // tranches horaires 
                //DateTime addHour = newAppointment.datHour.AddHours(1);
                //var timeSpot = db.appointments.Where(x => x.idBroker == newAppointment.idBroker).Where(x => x.datHour >= newAppointment.datHour & x.datHour <= addHour).SingleOrDefault();

                // si le rdv avec ce broker existe pas dans la dbb, message d'erreur
                if (db.appointments.Any(x => x.idBroker == newAppointment.idBroker) && db.appointments.Any(x => x.datHour == newAppointment.datHour))
                {
                    // message d'erreur dans une alert js et retour à la dernière page
                    return Content("<script type='text/javascript'>alert('Le courtier a déjà un rendez vous pour le crénaux horaire spécifié.'); history.back();</script>");
                }
                
                // sinon insert into
                else
                {
                    // insert into query
                    string insertAppointmentQuery = "INSERT INTO [dbo].[appointments]([datHour], [subject], [idBroker], [idCustomer])" +
                                        "VALUES ('" + newAppointment.datHour + "', '" + newAppointment.subject + "', " + newAppointment.idBroker + ", " + newAppointment.idCustomer + ");";
                    db.Database.ExecuteSqlCommand(insertAppointmentQuery); // execution de la query
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
            }
            // sinon, renvoyer message d'erreur
            else
            {
                return Content("<script type='text/javascript'>Swal.fire('Vous ne pouvez pas prendre de rendez-vous pour une date passée.'); history.back();</script>");
            }
        }
    }
}

Module 3 - MVC/Agenda/diary/diary/Controllers/BrokerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using diary.Models; // ajout du modèle

namespace diary.Controllers
{
    public class BrokerController : Controller
    {
        private agendaEntities1 db = new agendaEntities1(); // nouvelle instance du modèle bdd
        // GET: Broker | Méthode permettant d'afficher le formulaire d'ajout de courtier
        public ActionResult AddBroker()
        {
            return View("AddBroker");
        }
        // POST: Broker | Méthode permettant d'ajouter un courtier dans la bdd lors d'un POST
        [HttpPost] 
        public ActionResult AddBroker(broker newBroker)
        {
            using(db) 
            {
                // si lastName ET firstName éxistent dans la base, afficher message d'erreur
                if ((db.brokers.Any(x => x.lastName == newBroker.lastName) && db.brokers.Any(x => x.firstName == newBroker.firstName)) || db.brokers.Any(x => x.mail == newBroker.mail))
                {
                    ViewBag.DuplicateMessage = "Le courtier que vous essayez d'ajouter existe déjà dans la base de données";
                    return View("AddBroker");
                }
                // sinon INSERT INTO
                else
                {
                    db.brokers.Add(newBroker); // INSERT INTO db l'objet broker
                    db.SaveChanges(); // sauvegarde dans la bdd
                    ViewBag.SuccesMessage = "Courtier ajouté";
                }
            }
            ModelState.Clear(); // supprime les erreurs du model
            return View("AddBroker");
        }
        // GET: ListBroker | Méthode permettant d'afficher la liste des courtiers
        public ActionResult ListBrokers()
        {
            // requête linq
            var brokersList = from m in db.brokers
                              select m;
            ModelState.Clear();
            return View("ListBrokers", brokersList.ToList());
        }
        // GET: DetailBroker | Méthode permettant d'afficher le détail d'un courtier
        public ActionResult DetailBroker(int? id)
        {
            broker SelectedBroker = db.brokers.Find(id); // requete de selection par l'id
            // si l'id est null ou non renseigné, ou que l'objet selectedbroker renvoyer vue erreur
            if (id == null || SelectedBroker == null)
            {
                return View("Error404");
            }
            return View("DetailBroker", SelectedBroker);
        }
        // POST: DetailBroker | Méthode permettant de modifier le courtier dans la bdd lors d'un POST
        [HttpPost]
        public ActionResult DetailBroker(broker broker)
        {
            using (db)
            {
                db.Entry(broker).State = EntityState.Modified; // UPDATE
                db.SaveChanges(); // Sauvegarde dans la bdd
                ViewBag.ModifySuccess = "Courtier modifié avec succès"; // Message de succes affiché dans la vue via la propriétée de ViewBag 
            }
            return RedirectToAction("DetailBroker/" + broker.idBroker);
        }
        // GET: DeleteBroker | Permet d'afficher la page de suppression d'un courtier
        [HttpGet]
        public ActionResult DeleteBroker(int? id)
        {
            // select query
            string selectOneBrokerQuery =   "SELECT [idBroker], [lastName], [firstName], [mail], [phoneNumber]" +
                                            "FROM [dbo].[brokers]" +
                                            "WHERE [idBroker] = " + id + ";";
            // si l'id est null, erreur404
            if (id == null)
            {
                return View("Error404");
            }
            // sinon, retourner la vue "confirmation de suppression" avec le broker sélectionné
            else
            {
                // execution de la query passé dans l'objet selectedBroker
                broker SelectedBroker = db.brokers.SqlQuery(selectOneBrokerQuery, id).SingleOrDefault();
                // si selectedBroker est null, erreur 404
                if (SelectedBroker == null)
                {
                    return View("Error404");
                }
                return View("DeleteBroker", SelectedBroker);
            }
        }
        // POST: DeleteBroker | Permet de supprimer un courtier de la bdd
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBroker(int? id, broker brokerToDelete)
        {
            // si l'id est null, erreur404
            // sinon, supprimer le broker ayant l'id sélectionné
            if (id == null)
            {
                return View("Error404");
            }
            else
            {
                // delete query
                string deleteBrokerQuery = "DELETE FROM [dbo].[brokers]" +
                                        "WHERE [idBroker] = " + id + ";";
                db.Database.ExecuteSqlCommand(deleteBrokerQuery); // execute la query
                return RedirectToAction("ListBrokers");
            }
        }
    }
}

Module 3 - MVC/Agenda/diary/diary/Views/Broker/AddBroker.cshtml
@* ajout du modèle dans la vue *@
@model diary.Models.broker
@{
    ViewBag.Title = "Ajout Courtier";
}

<h2>Ajouter un nouveau courtier</h2>
@* messages d'erreurs ou réussite insert *@
<span class="success-message">@ViewBag.SuccesMessage</span>
<span class="failure-message">@ViewBag.DuplicateMessage</span>
<div id="form_container" class="container rounded mt-2 text-center">
    @using (Html.BeginForm("AddBroker", "Broker"))
    {
        <div>
            <div class="form-group pt-2">
                @* label, input type text, message d'erreur *@
                @Html.LabelFor(model => model.lastName, new { @class = "label-hidden" })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "rounded failure-message mb-2" })
                @Html.TextBoxFor(model => model.lastName, new { placeholder = "Nom de famille", @class = "form-control" })
            </div>
            <div class="form-group mt-2">
                @Html.LabelFor(model => model.firstName, new { @class = "label-hidden" })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "rounded failure-message mb-2" })
                @Html.TextBoxFor(model => model.firstName, new { placeholder = "Prénom", @class = "form-control" })
            </div>
            <div class="form-group mt-2">
                @Html.LabelFor(model => model.mail, new { @class = "label-hidden" })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "rounded failure-message mb-2" })
                @Html.TextBoxFor(model => model.mail, new { placeholder = "Adresse Mail", @class = "form-control" })
            </div>
            <div class="form-group mt-2">
                @Html.LabelFor(model => model.phoneNumber, new { @class = "label-hidden" })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "rounded failure-message mb-2" })
                @Html.TextBoxFor(model => model.phoneNumber, new { placeholder = "Numéro de télephone", @class = "form-control" })
            </div>
            <div class="mt-2 pb-2">
                <button id="submit" type="submit" class="btn btn-primary">Ajouter</button>
            </div>
        </div>
    }
</div>

Module 3 - MVC/Agenda/diary/diary/Views/Broker/DeleteBroker.cshtml
@model diary.Models.broker

@{
    ViewBag.Title = "Suppression de courtier";
}

<h2>Etes vous sûr(e) de vouloir supprimer ce client?</h2>

<div id="delete_form_container" class="container rounded mt-2 text-center">
    @using (Html.BeginForm("DeleteBroker", "Broker", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.idBroker)
        <div class="form-group pt-2">
            <p>
                @Html.DisplayNameFor(model => model.lastName)   <br />
                @Html.DisplayFor(model => model.lastName)
            </p>
        </div>
        <div class="form-group pt-2">
            <p>
                @Html.DisplayNameFor(model => model.firstName)  <br />
                @Html.DisplayFor(model => model.firstName)
            </p>
        </div>
        <div class="form-group pt-2">
            <p>
                @Html.DisplayNameFor(model => model.mail)   <br />
                @Html.DisplayFor(model => model.mail)
            </p>
        </div>
        <div class="form-group pt-2">
            <p>
                @Html.DisplayNameFor(model => model.phoneNumber)    <br />
                @Html.DisplayFor(model => model.phoneNumber)
            </p>
        </div>
        <div>
            <button id="delete_submit" type="submit" class="btn btn-danger mb-2">SUPPRIMER</button>
        </div>
    }
</div>

Module 3 - MVC/Agenda/diary/diary/Views/Broker/DetailBroker.cshtml
@model diary.Models.broker
@{
    ViewBag.Title = "Détails du courtier";
}

<h2>Détails du courtier</h2>
<span>@ViewBag.ModifySuccess</span>
<div class="container table-responsive">
    @using (Html.BeginForm("DetailBroker", "Broker", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.idBroker)
        <table>
            @*Affichage du nom des attribut du model dans les colonnes*@
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.lastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.firstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.mail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phoneNumber)
                </th>
            </tr>
            @*affichage des informations du broker sélectionné dans la value de l'input*@
            <tr>
                <td>
                    @Html.TextBoxFor(model => model.lastName, new { value = Model.lastName, @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.firstName, new { value = Model.firstName, @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.mail, new { value = Model.mail, id = "mail-input", @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(model => model.phoneNumber, new { value = Model.phoneNumber, @class = "form-control" })
                </td>
            </tr>
            @*Messages d'erreurs*@
            <tr>
                <td>
                    @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "rounded failure-message" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "rounded failure-message" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.mail, "", new { @class = "rounded failure-message" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "rounded failure-message" })
                </td>
            </tr>
        </table>
        <div class="row">
            <div class="col-12 text-center mt-3">
                <button type="submit" class="btn btn-info">Modifier</button>
            </div>
        </div>
    }
</div>

Module 3 - MVC/Agenda/diary/diary/Views/Broker/ListBrokers.cshtml
@model IEnumerable<diary.Models.broker>
@{
    ViewBag.Title = "liste des courtiers";
}

<h2>Liste des courtiers</h2>

<div class="container mt-2 table-responsive">
    <table class="table table-sm table-hover table-striped table-dark">
        <thead>
            <tr class="thead-dark">
                <th>
                    @Html.DisplayNameFor(model => model.lastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.firstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.mail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phoneNumber)
                </th>
                <th></th>
            </tr>
        </thead>
        <!--pour tous les items dans le model, afficher une ligne dans le tableau-->
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.lastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.firstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phoneNumber)
                </td>
                <td>
                    @Html.ActionLink("Rendez-vous", "AddAppointment", "Appointment", new { id = item.idBroker }, new { @class = "mr-2" })
                    @Html.ActionLink("Détails | Modifier", "DetailBroker", "Broker", new { id = item.idBroker }, null)
                    @Html.ActionLink("X", "DeleteBroker", "Broker", new { id = item.idBroker }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>
</div>